Repository bengreenier/browserd, pull requests merged in 2019-06, with the labels that each got.

#3 Add CI pipeline ⚙
  Dockerfile
  README.md
  azure-pipelines.yml
Labels: enhancement

#5 fix bug in azure-pipeline.yml 🐛
  azure-pipelines.yml
Labels: bug

#12 Add sonarQube support 🎖
  .gitignore
  README.md
  package-lock.json
  package.json
Labels: enhancement

#14 Adding signaling info to readme and removing peerService
  README.md
  src/__tests__/signal.spec.ts
  src/browserd.ts
  src/index.ts
  src/preload.ts
  src/signal.ts
Labels: documentation, enhancement

#10 Add Deploy to Azure button ☁
  README.md
  azuredeploy.json
Labels: enhancement

#21 Supporting Twilio's STUN/TURN service
  README.md
  azuredeploy.json
  package-lock.json
  package.json
  src/__tests__/index.spec.ts
  src/__tests__/signal.spec.ts
  src/__tests__/turn.spec.ts
  src/browserd.ts
  src/preload.ts
  src/turn.ts
Labels: enhancement
